services:
  nodejs:
    build: ./
    restart: always

  questdb:
    image: questdb/questdb:latest
    ports:
      - "8812:8812"  # ახალი 
      - "9000:9000"    # Web UI
      - "9009:9009"    # ILP (Influx Line Protocol)
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
  caddy:
      image: caddy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./caddyfile:/etc/caddy/Caddyfile
      restart: unless-stopped

volumes:
  grafana-storage: